use quarry_lib::edit::build_batch;
use quarry_lib::edit::decide::{ColumnEdit, EditInfo, PkColumn};
use quarry_lib::edit::sql::{
    build_deletes, build_inserts, build_updates, cast_target, quote_ident, value_choices, CellEdit,
    RowDelete, RowEdit, RowInsert, StatementKind,
};
use tokio_postgres::types::{Kind, Type};

fn editable(name: &str, cast_type: &str) -> ColumnEdit {
    ColumnEdit {
        editable: true,
        column_name: Some(name.to_string()),
        cast_type: Some(cast_type.to_string()),
        reason: None,
        insertable: true,
        insert_reason: None,
        choices: None,
        has_default: false,
    }
}

fn read_only() -> ColumnEdit {
    ColumnEdit {
        editable: false,
        // Filled even though the column is read-only: RETURNING has to
        // name the generated key, and this is the fixture that proves
        // `build_inserts` returns it. With `None` here the expected SQL
        // below silently loses `"id"`.
        column_name: Some("id".to_string()),
        cast_type: Some("\"pg_catalog\".\"int4\"".to_string()),
        reason: Some("primary key".to_string()),
        // A serial key: the database generates it.
        insertable: false,
        insert_reason: Some("generated by the database".to_string()),
        choices: None,
        has_default: true,
    }
}

/// `select id, email, plan from users`, id being the key.
fn users() -> EditInfo {
    EditInfo {
        editable: true,
        reason: None,
        insertable: true,
        insert_reason: None,
        schema: Some("public".to_string()),
        table: Some("users".to_string()),
        pk: vec![PkColumn {
            name: "id".to_string(),
            result_index: 0,
        }],
        columns: vec![
            read_only(),
            editable("email", "\"pg_catalog\".\"text\""),
            editable("plan", "\"pg_catalog\".\"text\""),
        ],
    }
}

#[test]
fn a_plain_type_casts_through_text() {
    assert_eq!(cast_target(&Type::INT4), "\"pg_catalog\".\"int4\"");
    assert_eq!(cast_target(&Type::TEXT), "\"pg_catalog\".\"text\"");
}

#[test]
fn an_array_type_keeps_its_brackets() {
    // Not `_text`, which is the internal spelling and casts to nothing
    // the user would recognise.
    assert_eq!(cast_target(&Type::TEXT_ARRAY), "\"pg_catalog\".\"text\"[]");
}

#[test]
fn an_identifier_is_quoted_and_embedded_quotes_are_doubled() {
    assert_eq!(quote_ident("users"), "\"users\"");
    assert_eq!(quote_ident("my\"table"), "\"my\"\"table\"");
}

#[test]
fn one_edited_cell_becomes_one_update() {
    let edits = vec![RowEdit {
        row: 4,
        pk: vec!["7".to_string()],
        cells: vec![CellEdit {
            column: 1,
            value: Some("a@b.co".to_string()),
        }],
    }];

    let statements = build_updates(&users(), &edits).expect("should build");

    assert_eq!(statements.len(), 1);
    assert_eq!(
        statements[0].sql,
        "update \"public\".\"users\" set \"email\" = $1::text::\"pg_catalog\".\"text\" \
         where \"id\" = $2::text::\"pg_catalog\".\"int4\" \
         returning \"email\""
    );
    assert_eq!(
        statements[0].params,
        vec![Some("a@b.co".to_string()), Some("7".to_string())]
    );
    assert_eq!(statements[0].row, 4);
    assert_eq!(statements[0].returned, vec![1]);
}

#[test]
fn two_cells_in_one_row_become_one_statement() {
    let edits = vec![RowEdit {
        row: 0,
        pk: vec!["7".to_string()],
        cells: vec![
            CellEdit {
                column: 1,
                value: Some("a@b.co".to_string()),
            },
            CellEdit {
                column: 2,
                value: Some("pro".to_string()),
            },
        ],
    }];

    let statements = build_updates(&users(), &edits).expect("should build");

    assert_eq!(statements.len(), 1);
    assert!(
        statements[0].sql.contains("set \"email\" = $1")
            && statements[0].sql.contains(", \"plan\" = $2"),
        "sql was: {}",
        statements[0].sql
    );
    assert_eq!(statements[0].returned, vec![1, 2]);
}

#[test]
fn two_rows_become_two_statements() {
    let edits = vec![
        RowEdit {
            row: 0,
            pk: vec!["7".to_string()],
            cells: vec![CellEdit {
                column: 1,
                value: Some("a@b.co".to_string()),
            }],
        },
        RowEdit {
            row: 1,
            pk: vec!["8".to_string()],
            cells: vec![CellEdit {
                column: 1,
                value: Some("c@d.co".to_string()),
            }],
        },
    ];

    let statements = build_updates(&users(), &edits).expect("should build");
    assert_eq!(statements.len(), 2);
}

#[test]
fn null_binds_as_null_not_as_the_word() {
    let edits = vec![RowEdit {
        row: 0,
        pk: vec!["7".to_string()],
        cells: vec![CellEdit {
            column: 1,
            value: None,
        }],
    }];

    let statements = build_updates(&users(), &edits).expect("should build");
    assert_eq!(statements[0].params[0], None);
}

/// `select user_id, group_id, role from memberships`, the key being
/// both id columns.
fn memberships() -> EditInfo {
    EditInfo {
        editable: true,
        reason: None,
        insertable: true,
        insert_reason: None,
        schema: Some("public".to_string()),
        table: Some("memberships".to_string()),
        pk: vec![
            PkColumn {
                name: "user_id".to_string(),
                result_index: 0,
            },
            PkColumn {
                name: "group_id".to_string(),
                result_index: 1,
            },
        ],
        columns: vec![
            read_only(),
            read_only(),
            editable("role", "\"pg_catalog\".\"text\""),
        ],
    }
}

#[test]
fn a_composite_key_puts_every_column_in_the_where() {
    let info = memberships();

    let edits = vec![RowEdit {
        row: 0,
        pk: vec!["7".to_string(), "9".to_string()],
        cells: vec![CellEdit {
            column: 2,
            value: Some("admin".to_string()),
        }],
    }];

    let statements = build_updates(&info, &edits).expect("should build");
    assert!(
        statements[0].sql.contains("where \"user_id\" = $2")
            && statements[0].sql.contains("and \"group_id\" = $3"),
        "sql was: {}",
        statements[0].sql
    );
    assert_eq!(
        statements[0].params,
        vec![
            Some("admin".to_string()),
            Some("7".to_string()),
            Some("9".to_string())
        ]
    );
}

#[test]
fn editing_a_read_only_column_is_refused() {
    // The UI does not offer this. The generator refuses it anyway: a
    // frontend bug must not be able to write to a primary key.
    let edits = vec![RowEdit {
        row: 0,
        pk: vec!["7".to_string()],
        cells: vec![CellEdit {
            column: 0,
            value: Some("99".to_string()),
        }],
    }];

    let error = build_updates(&users(), &edits).expect_err("must refuse");
    assert!(
        format!("{error}").contains("not editable"),
        "error was: {error}"
    );
}

#[test]
fn a_wrong_number_of_key_values_is_refused() {
    let edits = vec![RowEdit {
        row: 0,
        pk: vec![],
        cells: vec![CellEdit {
            column: 1,
            value: Some("a@b.co".to_string()),
        }],
    }];

    let error = build_updates(&users(), &edits).expect_err("must refuse");
    assert!(
        format!("{error}").contains("primary key"),
        "error was: {error}"
    );
}

#[test]
fn a_result_that_is_not_editable_generates_nothing() {
    let mut info = users();
    info.editable = false;
    info.reason = Some("this result comes from a view".to_string());

    let edits = vec![RowEdit {
        row: 0,
        pk: vec!["7".to_string()],
        cells: vec![CellEdit {
            column: 1,
            value: Some("a@b.co".to_string()),
        }],
    }];

    build_updates(&info, &edits).expect_err("must refuse");
}

#[test]
fn no_edits_generate_no_statements() {
    let statements = build_updates(&users(), &[]).expect("should build");
    assert!(statements.is_empty());
}

#[test]
fn an_update_is_marked_as_an_update() {
    let edits = vec![RowEdit {
        row: 0,
        pk: vec!["7".to_string()],
        cells: vec![CellEdit {
            column: 1,
            value: Some("a@b.co".to_string()),
        }],
    }];

    let statements = build_updates(&users(), &edits).expect("should build");
    assert_eq!(statements[0].kind, StatementKind::Update);
}

#[test]
fn one_deleted_row_becomes_one_delete() {
    let deletes = vec![RowDelete {
        row: 4,
        pk: vec!["7".to_string()],
    }];

    let statements = build_deletes(&users(), &deletes).expect("should build");

    assert_eq!(statements.len(), 1);
    assert_eq!(
        statements[0].sql,
        "delete from \"public\".\"users\" \
         where \"id\" = $1::text::\"pg_catalog\".\"int4\" \
         returning \"id\""
    );
    assert_eq!(statements[0].params, vec![Some("7".to_string())]);
    assert_eq!(statements[0].row, 4);
    assert_eq!(statements[0].kind, StatementKind::Delete);
    // The RETURNING list is there to make the rowcount assert work, not
    // to feed the grid: a deleted row has nothing left to patch.
    assert!(statements[0].returned.is_empty());
}

#[test]
fn two_deleted_rows_become_two_deletes() {
    let deletes = vec![
        RowDelete {
            row: 0,
            pk: vec!["7".to_string()],
        },
        RowDelete {
            row: 1,
            pk: vec!["8".to_string()],
        },
    ];

    let statements = build_deletes(&users(), &deletes).expect("should build");
    assert_eq!(statements.len(), 2);
    assert_eq!(statements[0].params, vec![Some("7".to_string())]);
    assert_eq!(statements[1].params, vec![Some("8".to_string())]);
    assert_eq!(statements[1].row, 1);
}

#[test]
fn a_composite_key_delete_puts_every_column_in_the_where() {
    let deletes = vec![RowDelete {
        row: 0,
        pk: vec!["7".to_string(), "9".to_string()],
    }];

    let statements = build_deletes(&memberships(), &deletes).expect("should build");

    assert_eq!(
        statements[0].sql,
        "delete from \"public\".\"memberships\" \
         where \"user_id\" = $1::text::\"pg_catalog\".\"int4\" \
         and \"group_id\" = $2::text::\"pg_catalog\".\"int4\" \
         returning \"user_id\", \"group_id\""
    );
    assert_eq!(
        statements[0].params,
        vec![Some("7".to_string()), Some("9".to_string())]
    );
}

#[test]
fn a_wrong_number_of_key_values_is_refused_for_a_delete() {
    let deletes = vec![RowDelete { row: 0, pk: vec![] }];

    let error = build_deletes(&users(), &deletes).expect_err("must refuse");
    assert!(
        format!("{error}").contains("primary key"),
        "error was: {error}"
    );
}

#[test]
fn a_result_that_is_not_editable_deletes_nothing() {
    let mut info = users();
    info.editable = false;
    info.reason = Some("this result comes from a view".to_string());

    let deletes = vec![RowDelete {
        row: 0,
        pk: vec!["7".to_string()],
    }];

    build_deletes(&info, &deletes).expect_err("must refuse");
}

#[test]
fn no_deletes_generate_no_statements() {
    let statements = build_deletes(&users(), &[]).expect("should build");
    assert!(statements.is_empty());
}

#[test]
fn a_boolean_offers_true_and_false() {
    assert_eq!(
        value_choices(&Type::BOOL),
        Some(vec!["true".to_string(), "false".to_string()])
    );
}

#[test]
fn an_ordinary_type_offers_nothing() {
    assert_eq!(value_choices(&Type::TEXT), None);
    assert_eq!(value_choices(&Type::INT4), None);
}

#[test]
fn an_enum_offers_its_labels_in_declaration_order() {
    // Postgres reports enum labels in the order they were declared,
    // which is the type's own sort order — not alphabetical.
    let mood = Type::new(
        "mood".to_string(),
        16400,
        Kind::Enum(vec![
            "sad".to_string(),
            "ok".to_string(),
            "happy".to_string(),
        ]),
        "public".to_string(),
    );

    assert_eq!(
        value_choices(&mood),
        Some(vec![
            "sad".to_string(),
            "ok".to_string(),
            "happy".to_string()
        ])
    );
}

#[test]
fn a_domain_over_an_enum_offers_the_enums_labels() {
    let mood = Type::new(
        "mood".to_string(),
        16400,
        Kind::Enum(vec!["sad".to_string(), "ok".to_string()]),
        "public".to_string(),
    );
    let strict_mood = Type::new(
        "strict_mood".to_string(),
        16401,
        Kind::Domain(mood),
        "public".to_string(),
    );

    assert_eq!(
        value_choices(&strict_mood),
        Some(vec!["sad".to_string(), "ok".to_string()])
    );
}

#[test]
fn one_staged_row_becomes_one_insert() {
    let inserts = vec![RowInsert {
        row: 0,
        cells: vec![
            CellEdit {
                column: 1,
                value: Some("a@b.c".to_string()),
            },
            CellEdit {
                column: 2,
                value: Some("pro".to_string()),
            },
        ],
    }];

    let statements = build_inserts(&users(), &inserts).expect("should build");

    assert_eq!(statements.len(), 1);
    assert_eq!(
        statements[0].sql,
        "insert into \"public\".\"users\" (\"email\", \"plan\") \
         values ($1::text::\"pg_catalog\".\"text\", $2::text::\"pg_catalog\".\"text\") \
         returning \"id\", \"email\", \"plan\""
    );
    assert_eq!(
        statements[0].params,
        vec![Some("a@b.c".to_string()), Some("pro".to_string())]
    );
    assert_eq!(statements[0].kind, StatementKind::Insert);
    // Every result column that maps to a real table column is returned,
    // in result order, so the generated key lands in the right cell.
    assert_eq!(statements[0].returned, vec![0, 1, 2]);
    assert_eq!(statements[0].row, 0);
}

#[test]
fn an_untouched_column_is_left_out_of_the_statement() {
    // Absent from `cells` means absent from the column list, which is
    // what makes the database apply its default.
    let inserts = vec![RowInsert {
        row: 0,
        cells: vec![CellEdit {
            column: 1,
            value: Some("a@b.c".to_string()),
        }],
    }];

    let statements = build_inserts(&users(), &inserts).expect("should build");

    // Pinned whole rather than by substring: `plan` still appears in
    // the RETURNING list — it is the column list it must stay out of,
    // and that is what makes the database apply the default.
    assert_eq!(
        statements[0].sql,
        "insert into \"public\".\"users\" (\"email\") \
         values ($1::text::\"pg_catalog\".\"text\") \
         returning \"id\", \"email\", \"plan\""
    );
    assert_eq!(statements[0].params.len(), 1);
}

#[test]
fn an_explicit_null_is_bound_as_null() {
    // Distinct from untouched: this overrides a default with NULL.
    let inserts = vec![RowInsert {
        row: 0,
        cells: vec![CellEdit {
            column: 2,
            value: None,
        }],
    }];

    let statements = build_inserts(&users(), &inserts).expect("should build");

    assert!(statements[0].sql.contains("(\"plan\")"));
    assert_eq!(statements[0].params, vec![None]);
}

#[test]
fn a_row_with_nothing_staged_uses_default_values() {
    let inserts = vec![RowInsert {
        row: 0,
        cells: vec![],
    }];

    let statements = build_inserts(&users(), &inserts).expect("should build");

    assert_eq!(
        statements[0].sql,
        "insert into \"public\".\"users\" default values returning \"id\", \"email\", \"plan\""
    );
    assert!(statements[0].params.is_empty());
}

#[test]
fn a_generated_column_is_refused_a_value() {
    // The frontend never offers this; refusing here means a frontend
    // bug cannot become a failed transaction or a wrong write.
    let inserts = vec![RowInsert {
        row: 0,
        cells: vec![CellEdit {
            column: 0,
            value: Some("7".to_string()),
        }],
    }];

    let error = build_inserts(&users(), &inserts).expect_err("should refuse");

    assert!(
        format!("{error:?}").contains("cannot take a value"),
        "was: {error:?}"
    );
}

#[test]
fn a_result_that_is_not_insertable_is_refused() {
    let mut info = users();
    info.insertable = false;
    info.insert_reason =
        Some("add code to the query to insert rows — it is NOT NULL with no default".to_string());

    let error = build_inserts(
        &info,
        &[RowInsert {
            row: 0,
            cells: vec![],
        }],
    )
    .expect_err("should refuse");

    assert!(format!("{error:?}").contains("NOT NULL"), "was: {error:?}");
}

#[test]
fn no_staged_rows_produce_no_statements() {
    assert!(build_inserts(&users(), &[])
        .expect("should build")
        .is_empty());
}

#[test]
fn two_staged_rows_produce_two_statements_in_order() {
    let inserts = vec![
        RowInsert {
            row: 0,
            cells: vec![CellEdit {
                column: 1,
                value: Some("a".to_string()),
            }],
        },
        RowInsert {
            row: 1,
            cells: vec![CellEdit {
                column: 1,
                value: Some("b".to_string()),
            }],
        },
    ];

    let statements = build_inserts(&users(), &inserts).expect("should build");

    assert_eq!(statements.len(), 2);
    assert_eq!(statements[0].row, 0);
    assert_eq!(statements[1].row, 1);
}

#[test]
fn a_batch_runs_updates_then_deletes_then_inserts() {
    let edits = vec![RowEdit {
        row: 0,
        pk: vec!["1".to_string()],
        cells: vec![CellEdit {
            column: 1,
            value: Some("a@b.c".to_string()),
        }],
    }];
    let deletes = vec![RowDelete {
        row: 1,
        pk: vec!["2".to_string()],
    }];
    let inserts = vec![RowInsert {
        row: 0,
        cells: vec![CellEdit {
            column: 1,
            value: Some("c@d.e".to_string()),
        }],
    }];

    let statements = build_batch(&users(), &edits, &deletes, &inserts).expect("should build");

    let kinds: Vec<StatementKind> = statements.iter().map(|s| s.kind).collect();
    assert_eq!(
        kinds,
        vec![
            StatementKind::Update,
            StatementKind::Delete,
            StatementKind::Insert
        ]
    );
}
